### ISSUE TITLE
issue while launching jnlp with Adapt

### ISSUE THREAD

**Issue by NetOps-spectrum** [AdoptOpenJDK/IcedTea-Web#558]
```
Selecting proxy for: http://<>:<>/$Product/<>.jnlp
Selecting proxy for: http://<>:<>/$Product/<>.jnlp
Selected proxies: [DIRECT]

netx: Read Error: Could not read or parse the JNLP file. (java.lang.NullPointerException: name can't be null (name can't be null))

net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.
    at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)
    at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)
    at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)
    at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)
    at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
    at java.security.AccessController.doPrivileged(Native Method)
    at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210)
Caused by: java.io.IOException: java.lang.NullPointerException: name can't be null
    at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:318)
    at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:240)
    at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)
    at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)
    at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)
    at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)
    ... 6 more
Caused by: java.lang.NullPointerException: name can't be null
    at java.io.FilePermission.init(FilePermission.java:205)
    at java.io.FilePermission.<init>(FilePermission.java:305)
    at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
    at java.io.FileInputStream.<init>(FileInputStream.java:127)
    at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:316)
    ... 11 more

Downloading http://<>:<>/$Product/<>.jnlp using http://<>:<>/$Product/<>.jnlp (encoding : null)

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(String.java:1927)
    at net.sourceforge.jnlp.cache.CacheUtil.pathToURLPath(CacheUtil.java:555)
    at net.sourceforge.jnlp.cache.CacheUtil.getCacheFileIfExist(CacheUtil.java:539)
    at net.sourceforge.jnlp.cache.CacheUtil.getCacheFile(CacheUtil.java:511)
    at net.sourceforge.jnlp.cache.CacheEntry.<init>(CacheEntry.java:61)
    at net.sourceforge.jnlp.cache.ResourceDownloader.downloadFile(ResourceDownloader.java:412)
    at net.sourceforge.jnlp.cache.ResourceDownloader.downloadResource(ResourceDownloader.java:364)
    at net.sourceforge.jnlp.cache.ResourceDownloader.run(ResourceDownloader.java:118)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Disconnecting sun.net.www.protocol.http.HttpURLConnection:http://<>:<>/$Product/<>.jnlp
```

**Comment by sclassen** [comment]
The reason is that some JNLP file cannot be downloaded.
Without a complete log an the JNLP file(s) it is hard to tell what exactly is going wrong

**Comment by NetOps-spectrum** [comment]
Attached are the requested logs


[jnlp.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4032107/jnlp.zip)


And The log files shows the NullPointerException:

 

                                Connecting http://10.254.126.216:8080/spectrum/oneclick.jnlp\

done http://10.254.126.216:8080/spectrum/oneclick.jnlp\

Selecting proxy for: http://10.254.126.216:8080/spectrum/oneclick.jnlp\

Selected proxies: [DIRECT]\

netx: Read Error: Could not read or parse the JNLP file. (java.lang.NullPointerException: name can't be null (name can't be null))\

net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.\

        at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)\

        at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)\

        at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)\

        at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)\

        at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)\

        at java.security.AccessController.doPrivileged(Native Method)\

        at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210)\

**Comment by sclassen** [comment]
can you try the following:
1. clear the cache
1. make sure the following are reachable:
   * [http://10.254.126.216:8080/spectrum/oneclick.jnlp](http://10.254.126.216:8080/spectrum/oneclick.jnlp)
   * [http://10.254.126.216:8080/spectrum/cryptoj.jnlp](http://10.254.126.216:8080/spectrum/cryptoj.jnlp)
1. start the jnlp and see if error is still there

To test reachability you can try to download the jnlp file using the browser

**Comment by NetOps-spectrum** [comment]
So YES of course all is reachable.. See attahced



[java.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4089346/java.zip)

**Comment by sclassen** [comment]
one last thing to try, then I am out of my wits...

Can you post the content of your `%USER_HOME%/.cache/icedtea-web/cache/recently_used`
Maybe something shows up in there

**Comment by NetOps-spectrum** [comment]
The changed in iced-tea settings to LOW security and was working for few days. Now again not working

Attached is the log
[recently_used.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4135411/recently_used.txt)

**Comment by sclassen** [comment]
Can you delete the directory `%user.home%\.cache\icedtea-web\cache`

**Comment by NetOps-spectrum** [comment]
Customer already applied but still facing issue, following is customer reply:

not helped. Now not occured same error but HUNG on starting OC

 

and customer shared the attached screenshot of the error.

<img width="1015" alt="Screenshot 2020-02-17 at 17 42 31" src="https://user-images.githubusercontent.com/58945429/76061070-b855da00-5fa8-11ea-81ed-667cf6b45f7c.png">

**Comment by sclassen** [comment]
@judovana this is a 1.8 installation. I do not know what further to try to debug this issue. Any ideas?

**Comment by NetOps-spectrum** [comment]
Any update on this as there are multiple customers facing this issue?

**Comment by douph1** [comment]
Hi,
Inside jnlp.zip I see :
line: 5 <jnlp spec="1.0+" codebase="http://10.254.126.216:8080/spectrum" href="/spectrum/oneclick.jnlp" xmlns="http://www.w3.org/1999/xhtml">

I think codebase + href must match a good url which is not the case
try something like this ( dont duplicate "spectrum"  ) :
<jnlp spec="1.0+" codebase="http://10.254.126.216:8080/spectrum/" href="oneclick.jnlp" xmlns="http://www.w3.org/1999/xhtml">

If not sufficient take a look at https://github.com/AlBundy33/JaNeLa  to valide/debug your Jnlp via you http online url

**Comment by NetOps-spectrum** [comment]
Here is the output customer sent.

 

net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize application. The application has not been initialized, for more information execute javaws from the command line.

    at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:822)

    at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:531)

    at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:945)

Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: A fatal error occurred while trying to verify jars. An exception has been thrown in class JarCertVerifier. Being unable to read the cacerts or trusted.certs files could be a possible cause for this exception.: error in opening zip file

    at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:739)

    at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:338)

    at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:421)

    at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:495)

    at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:468)

    at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:814)

    ... 2 more

**Comment by NetOps-spectrum** [comment]
Any Update?

**Comment by sclassen** [comment]
This issue is on the 1.8 branch.
You can try https://openwebstart.com which is based on the 2.0 branch

**Comment by NetOps-spectrum** [comment]
Resolved now, can close the issue
